name: school_website
description: A new Flutter project for a school website.

publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust based on your Flutter version

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 # Example, check for latest version
  #file_picker: ^5.3.3
  #path_provider: ^2.1.1
  file_picker: ^5.3.3  # For file selection
  path_provider: ^2.1.1 # For directory access


  # Add other packages here if you use them, e.g., go_router, photo_view

  cupertino_icons: ^1.0.6
  intl: 0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Or your preferred linter

flutter:
  uses-material-design: true
  assets:
    - assets/images/school_logo.png
    - assets/images/gallery/ # Includes all subdirectories for gallery
    - assets/images/gallery/sports_day/image1.jpg # Example
    - assets/images/gallery/annual_function/image2.jpg # Example
    - assets/data/result/2025/class_10_results.json
    - assets/data/class_12_results.json
    - assets/data/result/
  #  - assets/fonts/ # If you have custom font files